[package]
name = "nine-mens-morris"
version = "0.1.0"
authors = ["Joost Ole Seddig <jst_sddg@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
